name: Artifact Admin Portal Web Build

on:
  workflow_dispatch: # Manual trigger
    inputs:
      version:
          required: true
          description: "Enter the version to deploy"
          default: "v1.0.0"
          type: string

jobs:
  build:
    name: Build React Web and Docker Image
    runs-on: ubuntu-latest

    steps:
    # Log user input and other variables
    - name: Log user input and context
      run: |
        echo "Version: ${{ github.event.inputs.version }}"
        echo "GitHub Run Number: ${{ github.run_number }}"
        echo "Branch/Ref: ${{ github.ref }}"
        echo "Triggered by: ${{ github.actor }}"
        
    # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setting up the Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    # 3. Get Dependencies
    - name: Install Dependencies
      run: npm ci

    # 4. Build React Web and output to './build' directory
    - name: Build React Web
      run: npm run build

    # 5. Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t poisum-admin-portal-image-artifact:${{ github.event.inputs.version }} .
    
    # 6. Save Docker Image
    - name: Save Docker Image as Archive
      run: |
        docker save poisum-admin-portal-image-artifact:${{ github.event.inputs.version }} | gzip > poisum-admin-portal-image-artifact-${{ github.event.inputs.version }}.tar.gz

    # 7. Upload Artifact for staging or development
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: poisum-admin-portal-image-artifact-${{ github.event.inputs.version }}
        path: ./poisum-admin-portal-image-artifact-${{ github.event.inputs.version }}.tar.gz